# Generated by Django 5.2.14 on 2026-06-01 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church_members', '0003_member_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('SERVICE', 'Church Service'), ('YOUTH', 'Youth Activity'), ('COMMITTEE', 'Committee Meeting'), ('OUTREACH', 'Outreach Program'), ('CHOIR', 'Choir Activity'), ('SPECIAL', 'Special Event')], max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('registration_required', models.BooleanField(default=False)),
                ('attendees', models.ManyToManyField(blank=True, related_name='registered_events', to='church_members.member')),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='church_members.member')),
            ],
        ),
    ]
