# Generated by Django 5.2.14 on 2026-06-10 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=timezone.now
            ),
            preserve_default=False,
        ),

        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='created_events',
                to=settings.AUTH_USER_MODEL,
            ),
        ),

        migrations.AddField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(
                default=True
            ),
        ),

        migrations.AddField(
            model_name='event',
            name='max_attendees',
            field=models.PositiveIntegerField(
                blank=True,
                null=True
            ),
        ),

        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(
                auto_now=True
            ),
        ),

        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(
                blank=True,
                default=''
            ),
            preserve_default=False,
        ),

        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(
                blank=True,
                default='',
                max_length=255
            ),
            preserve_default=False,
        ),

        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(
                max_length=200
            ),
        ),
    ]