# Generated by Django 5.2.14 on 2026-07-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_created_at_event_created_by_event_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recurrence',
            field=models.CharField(choices=[('NONE', 'None'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='NONE', help_text='Set a repeat pattern for events that occur on the same schedule each week or day.', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_day',
            field=models.CharField(blank=True, choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], default='', help_text='Use this for weekly recurring events to specify the repeating weekday.', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_end_date',
            field=models.DateField(blank=True, help_text='Optional end date for recurring events. Leave blank for an open recurrence.', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(help_text='Enter a full date and time. Example: 2026-07-06 11:00 or 2026-07-06T11:00:00Z'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(help_text='Enter a full date and time. Example: 2026-07-06 09:00 or 2026-07-06T09:00:00Z'),
        ),
    ]
