# Generated by Django 5.2.14 on 2026-07-01 12:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_recurrence_event_recurrence_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_date',
        ),
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Enter the date and time for the event. Example: 2026-07-06 09:00 or 2026-07-06T09:00:00Z'),
            preserve_default=False,
        ),
    ]
