# Generated by Django 5.2.14 on 2026-05-31 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_members', '0001_initial'),
        ('committees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='committees',
            field=models.ManyToManyField(blank=True, to='committees.committee'),
        ),
    ]
