# Generated by Django 5.2.14 on 2026-06-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='church_role',
        ),
        migrations.AddField(
            model_name='user',
            name='church_role_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='interests_and_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_profile_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='receive_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='programme_of_study',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='year_of_study',
            field=models.CharField(blank=True, choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year'), ('5', 'Fifth Year'), ('POSTGRAD', 'Postgraduate')], default='1', max_length=20),
            preserve_default=False,
        ),
    ]
