# Generated by Django 5.2.14 on 2026-05-31 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_members', '0002_member_committees'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('SUPER_USER', 'Super User'), ('ADMIN_USER', 'Admin User'), ('HIGH_PRIVILEGE_USER', 'High Privilege User'), ('MEMBER', 'Member')], default='MEMBER', max_length=30),
        ),
    ]
