# Generated by Django 5.2.14 on 2026-06-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_members', '0002_remove_user_church_role_user_church_role_description_and_more'),
        ('committees', '0002_committee_is_active_committee_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='residential_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='residential_apostle_area',
        ),
        migrations.RemoveField(
            model_name='user',
            name='school_residential_address',
        ),
        migrations.AddField(
            model_name='user',
            name='committees',
            field=models.ManyToManyField(blank=True, related_name='members', to='committees.committee'),
        ),
        migrations.AlterField(
            model_name='user',
            name='church_role_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_profile_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='programme_of_study',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='year_of_study',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
