# Generated by Django 5.2.14 on 2026-06-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='committee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='committee',
            name='name',
            field=models.CharField(choices=[('CATERING', 'Catering Committee'), ('MUSIC', 'Music Committee'), ('ORGANIZING', 'Organizing Committee'), ('FINANCE', 'Finance Committee'), ('DRAPO', 'DRAPO Committee'), ('COMMUNICATION', 'Communication Committee'), ('TESTIFY', 'Testify Committee'), ('FLOWERING', 'Flowering Committee'), ('SECRETARIAL', 'Secretarial Committee')], max_length=50, unique=True),
        ),
    ]
