# Generated by Django 5.2.14 on 2026-06-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0002_committee_is_active_committee_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='committee',
            name='meeting_schedule',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='committee',
            name='purpose',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='committee',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
