# Generated by Django 5.2.14 on 2026-06-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0004_committeemembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeeposition',
            name='position_type',
            field=models.CharField(choices=[('CHAIRPERSON', 'Chairperson'), ('VICE_CHAIRPERSON', 'Vice Chairperson'), ('SECRETARY', 'Secretary'), ('VICE_SECRETARY', 'Vice Secretary'), ('TREASURER', 'Treasurer'), ('VICE_TREASURER', 'Vice Treasurer'), ('MEMBER', 'Member')], default='MEMBER', max_length=30),
        ),
    ]
