# Generated by Django 5.2.14 on 2026-06-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('MINUTES', 'Meeting Minutes'), ('CONSTITUTION', 'Constitution'), ('REPORT', 'Report'), ('GUIDELINE', 'Guideline'), ('FINANCIAL', 'Financial Document'), ('CIRCULAR', 'Circular'), ('POLICY', 'Policy'), ('OTHER', 'Other')], max_length=30),
        ),
    ]
