# Generated by Django 5.2.14 on 2026-06-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [

        migrations.RenameField(
            model_name='visitor',
            old_name='residential_address',
            new_name='address',
        ),

        migrations.RemoveField(
            model_name='visitor',
            name='converted_to_member',
        ),

        migrations.RemoveField(
            model_name='visitor',
            name='first_visit_date',
        ),

        migrations.AddField(
            model_name='visitor',
            name='follow_up_status',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('PENDING', 'Pending'),
                    ('CONTACTED', 'Contacted'),
                    ('VISITED', 'Visited'),
                    ('JOINED', 'Joined'),
                ],
                default='PENDING'
            ),
        ),

        migrations.AddField(
            model_name='visitor',
            name='visit_date',
            field=models.DateField(
                null=True,
                blank=True
            ),
        ),

        migrations.AlterField(
            model_name='visitor',
            name='phone_number',
            field=models.CharField(
                max_length=30,
                blank=True
            ),
        ),
    ]