# Generated by Django 5.2.14 on 2026-06-24 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_rename_residential_address_visitor_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='visit_date',
            field=models.DateField(default=datetime.date(2026, 6, 24)),
            preserve_default=False,
        ),
    ]
