# Generated by Django 5.2.14 on 2026-06-23 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_media_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='uploaded_by',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
