# Generated by Django 5.2.14 on 2026-06-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_commentreply_mediagallery_postreaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='privacy',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('MEMBERS', 'Members Only'), ('PRIVATE', 'Only Me')], default='MEMBERS', max_length=20),
        ),
    ]
